image: guix
packages:
  - make
  - hut
  - emacs-no-x
  - emacs-ox-html-stable-ids
sources:
  - https://git.sr.ht/~abcdw/emacs-arei
tasks:
  - readme: |
      cd emacs-arei

      # Deploy readme only when abcdw pushes.  Managing shared secrets
      # without organizations and teams is too cumbersome.
      if [[ "$BUILD_SUBMITTER" == "git.sr.ht" ]] && \
         [[ "$JOB_URL" =~ ^https://builds.sr.ht/~abcdw/job/.*$ ]]; then
        make deploy-README.html
      fi
oauth: git.sr.ht/REPOSITORIES:RW git.sr.ht/PROFILE:RO
triggers:
  - action: email
    condition: failure
    to: ~abcdw/rde-devel@lists.sr.ht
